<?php

namespace app\oauth2\widgets;

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;

/**
 * Created by PhpStorm.
 * User: zhangshuang
 * Date: 2019/7/24
 * Time: 2:32 PM
 */
class CommonWidget extends AuthChoice
{
    public $clientKey;
    public $imgUrl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $url = $this->createClientUrl($this->getClients()[$this->clientKey]);
        $content = <<<HTML
    <div class='col-lg-1'>
        <div style='height: 40px; width: 40px'>
                <a class='thumbnail' href='{$url}' title='{$this->clientKey}'><img src='{$this->imgUrl}'></a>
        </div>
    </div>
HTML;


        $content .= Html::endTag('div');
        return $content;
    }
}